name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 16 ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.*') }}
          restore-keys: |
            gradle-${{ runner.os }}
            gradle-
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
      - name: Prepare
        run: ./gradlew clean dependencies
      - name: Build
        run: ./gradlew assemble testClasses
      - name: Test
        run: ./gradlew test
      - name: Publish Test Report
        uses: scacap/action-surefire-report@c38a2d74b9840ae8950a4387ae02b637421d0f39 # v1.13.0
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
          check_name: Test Failures (${{ matrix.java-version }})
