name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO also test against the latest Kotlin version
        java-version: [ 17, 25, 26 ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.*') }}
          restore-keys: |
            gradle-${{ runner.os }}
            gradle-
      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          java-version-file: .sdkmanrc
      - name: Prepare
        run: ./gradlew clean dependencies
        env:
          ORG_GRADLE_PROJECT_javaVersion=${{ matrix.java-version }}
      - name: Build
        run: ./gradlew assemble testClasses
        env:
          ORG_GRADLE_PROJECT_javaVersion=${{ matrix.java-version }}
      - name: Test
        run: ./gradlew test
        env:
          ORG_GRADLE_PROJECT_javaVersion=${{ matrix.java-version }}
      - name: Publish Test Report
        uses: scacap/action-surefire-report@c38a2d74b9840ae8950a4387ae02b637421d0f39 # v1.13.0
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
          check_name: Test Failures (${{ matrix.java-version }})
